### ISSUE TITLE
Could not find environment ':sqlite-dev-env'

### ISSUE THREAD

**Issue by jamesyong** [sveri/closp#10]
Trying to create another project. Not sure why, but i got the above after running:

```
lein joplin migrate sqlite-dev-env
```

Worked okay before.

**Comment by sveri** [comment]
Ah, yes, I got hit by that too. You use leiningen 2.5.2 I assume?

There was a defect within joplin that caused this issue: https://github.com/juxt/joplin/issues/68

I just released a new version of closp, containing the fix. Please try again if it works for you now.

**Comment by jamesyong** [comment]
Yes, I am using lein 2.5.2. 
I tried to recreate the project, but have to change the joplin version in project.clj from 0.2.11 to 0.2.17 manually. Not sure why I am getting out-of-date version. So the problem is fixed for me.

**Comment by sveri** [comment]
Yea, I should have mentioned that. Added a FAQ entry for this.
