### ISSUE TITLE
Some Suggestions!

### ISSUE THREAD

**Issue by sniperliu** [sveri/closp#2]
Thanks for the effort to have such nice template!
I am playing with chestnut recently and feel the same thing.
One suggestion, maybe you could try joplin for the database migration.
It built on ragtime and provide multiple database support.

**Comment by sveri** [comment]
This looks interesting, did not know it before. I will see if I can integrate it into closp, which shouldn't be to hard.
It would be nice if there was the same abstraction over database access for the program logic. Something like jdbc on a higher level :-)

**Comment by sveri** [comment]
Yea, I will switch to joplin, should be fairly easy to do and there is no extra complexity added for an inital use of a new project. Looks good.
