### ISSUE TITLE
Change wording in repo title to remove Luminus reference

### ISSUE THREAD

**Issue by kahunamoore** [sveri/closp#24]
It seems there isn't anything related to Luminus in the generated project. Not a huge deal but I was confused when I went looking for it.

Of course, maybe Luminus is in the closp future and just not there yet.

I want to take a moment to thank you for this great template! While it's library choices don't match our needs (datomic vs sql) but those that do are great, thank you very much.

**Comment by kahunamoore** [comment]
Never mind... I didn't see some of the luminus-xxx libs and other libs it uses (e.g. mount) so I just assumed it wasn't based on luminus. The dependencies changed enough that I didn't recognize it. Then the _obvious_ directory structure similarities jumped out at me... doh!

Sorry for the noise. Closing the issue.

**Comment by sveri** [comment]
No problem, the thing is that closp is mainly built on top of luminus and lot of its stuff is the same. There are just a few notable differences here and there.
