### ISSUE TITLE
"lein migrate" not working

### ISSUE THREAD

**Issue by ovsemykin** [sveri/closp#28]
"Getting started
Open your command line and switch to a folder of your choice. Then execute the following commands:
lein new closp project-name -n foo.example 
cd project-name 
lein migrate "

not working.

(I use postgresql)

**Comment by sveri** [comment]
Hi @ovsemykin 

I am currently changing a lot of stuff in the template. The documenation is not adapted yet and will be only when I release a stable version. 
Part of it is, that migration will not be available anymore. If you want to use the latest stable version of closp execute this command: 

> lein new closp --template-version 0.2.0
