### ISSUE TITLE
generating a new project with a dash will create two project folders

### ISSUE THREAD

**Issue by sveri** [sveri/closp#3]
Running `lein new closp foo-bar` will generate a folder foo-bar with some content and the rest of the content will be in foo_bar.

**Comment by sventech** [comment]
Have you uploaded to Clojars since fixing this? I'm still seeing the issue. I worked around it by using an underscore.

**Comment by sveri** [comment]
No, I havn't and will do as soon as I got 5 minutes on my hand.

**Comment by sveri** [comment]
I just released it, but had no time to test, please go ahead and see if it works for you.

And thanks for your feedback :-)

**Comment by sventech** [comment]
Thanks! Works now.
