### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by jamesyong** [sveri/closp#9]
Hi,

I was trying out the steps under Usage; navigated to localhost:3449, and got a 'Page Not Found' page.
I am using windows 7 with java 8, if it matters. Thanks.

Regards

**Comment by jamesyong** [comment]
The application will run ok if I access localhost:3000. after executing the following:

```
lein new closp _projectname_ -n foo.bar
lein joplin migrate sqlite-dev-env
lein run 3000
```

There is a 'Page Not Found' page if I access localhost:3449 after executing the following:

```
lein new closp _projectname_ -n foo.bar
lein joplin migrate sqlite-dev-env
lein figwheel
```

**Comment by sveri** [comment]
Hi @jamesyong 

The default port for development and production is 3000, hence the error message when trying to access it via port 3449.
You can configure the port in `resources\closp.edn` via the :port key.

**Comment by jamesyong** [comment]
There is no connection when I access http://localhost:3000 after running:

```
lein new closp myprojectname -n foo.bar
lein joplin migrate sqlite-dev-env
lein figwheel
```

**Comment by sveri** [comment]
You also need to run:

```
lein repl
(start-dev-system)
```

To actually start the server and its components

**Comment by jamesyong** [comment]
It is working now. Thank you.

**Comment by sveri** [comment]
Ok, so I close this for now :-)
